MAX_EPOCHS: 20
MAX_TOKENS: 128
BUFFER_SIZE: 20000
BATCH_SIZE: 64
num_layers: 4
d_model: 128
dff: 512
num_heads: 8
dropout_rate: 0.1
beta_1: 0.9
beta_2: 0.98
epsilon: 1e-9
sentence_tbt: 'este é um problema que temos que resolver.' # to be translated
ground_truth: 'this is a problem we have to solve .'
save_keras: false